// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetTickets() {
  return window['go']['internal']['OrderHub']['GetTickets']();
}

export function Init(arg1) {
  return window['go']['internal']['OrderHub']['Init'](arg1);
}

export function OpenTerminal() {
  return window['go']['internal']['OrderHub']['OpenTerminal']();
}
