// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {internal} from '../models';
import {context} from '../models';

export function GetTickets():Promise<Array<internal.TicketView>>;

export function Init(arg1:context.Context):Promise<void>;

export function OpenTerminal():Promise<void>;
