// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AuthLogin(arg1, arg2) {
  return window['go']['internal']['OrderHub']['AuthLogin'](arg1, arg2);
}

export function Init(arg1) {
  return window['go']['internal']['OrderHub']['Init'](arg1);
}

export function OpenTerminal() {
  return window['go']['internal']['OrderHub']['OpenTerminal']();
}
